# Program-6:  Demonstrate the use of shape, size, reshape with various different test cases and inputs.

In [2]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5, 6])
print(arr_1d.shape) # Output: (6,)

# Reshape 1D array to 2D array (2 rows, 3 columns)
arr_2d = arr_1d.reshape(2, 3)
print(arr_2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Reshape using -1 for inferred dimension
arr_inferred = arr_1d.reshape(-1, 2)
print(arr_inferred)
# Output:
# [[1 2]
#  [3 4]


(6,)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [3]:
arr_inferred = arr_1d.reshape(-1, 1)
print(arr_inferred)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [3]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional arra
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
